language: viml

install:
    - sudo apt-get update -q
    - sudo apt-get install vim-gtk
    - sudo apt-get install docker

before_script:
    - vim --version
    - docker pull citizenstig/httpbin
    - docker run -d=true -p 8000:8000 citizenstig/httpbin
    - git clone https://github.com/thinca/vim-themis
    - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
    - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser

script:
    - vim-themis/bin/themis --reporter dot test
    - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL102.l:_=1 -c func_abort=1 autoload ftdetect plugin syntax
