version: 2
jobs:
  latest:
    docker:
      - image: thinca/vim:latest
      - image: citizenstig/httpbin
    steps: &steps
      - run:
          name: install git and curl
          command: apk add --no-cache git curl
      - checkout
      - run:
          name: test requirements
          command: |
            git clone https://github.com/thinca/vim-themis
            git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
            git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
      - run:
          name: test
          command: |
            vim-themis/bin/themis --reporter dot test
      - run:
          name: lint
          command: |
            sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL102.l:_=1 -c func_abort=1 autoload ftdetect plugin syntax
  oldest:
    docker:
      - image: thinca/vim:v7.4.566
      - image: citizenstig/httpbin
    steps: *steps
      

workflows:
  version: 2
  test:
    jobs:
      - latest
      - oldest
