name: CI
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  latest:
    runs-on: thinca/vim:latest
    services: &services
      httpbin:
        image: citizenstig/httpbin
    steps: &steps
    - uses: actions/checkout@v2
    - name: install git and curl
      run: apk add --no-cache git curl
    - name: test requirements
      run: |
        git clone https://github.com/thinca/vim-themis
        git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
        git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
    - name: test
      run: vim-themis/bin/themis --reporter dot test
    - name: lint
      run: sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL102.l:_=1 -c func_abort=1 autoload ftdetect plugin syntax
      
  oldest:
    runs-on: thinca/vim:v7.4.566
    services: *services
    steps: *steps
